### ISSUE TITLE
What is the definition of codeTypes?

### ISSUE THREAD

**Issue by devoren** [mgcrea/vision-camera-barcode-scanner#1]
Hello! I pass codeTypes: ['qr'] but it scans all code from code types. Do I understand correctly that if we pass codeTypes, this means that the scanner scans codes with a type from codeTypes?

**Comment by mgcrea** [comment]
Hey, indeed it's not currently implemented on the native side as I got sidetracked, but should add it pretty soon (meanwhile you can filter on the JS side but not ideal!).
