### ISSUE TITLE
Is it possible to limit scan area?

### ISSUE THREAD

**Issue by karel-suchomel-ed** [mgcrea/vision-camera-barcode-scanner#2]
Hello,
I tried the example app and the QR codes are being scanned even if they are outside of the scan area. I have a screen where in the middle is a 300x300 square camera window and I want to scan codes only if they are visible in this window. Still, currently, even if I set the width and height of the camera component, the codes are being scanned even when they are not visible. Do you have any implementation of this feature? I tried something like this in a different frame processor ([vision-camera-code-scanner](https://github.com/rodgomesc/vision-camera-code-scanner)) and it kind of worked, but here I couldn't manage to get it right.

```
const vf_x = 0
const vf_y = heightPercentageToDP('30%')
const vf_width = heightPercentageToDP('40%')
const vf_height = heightPercentageToDP('40%')
const win = Dimensions.get('window')

barcodes.forEach((barcode) => {
    const isPortal = win.height > win.width
    const rH = win.height / (isPortal ? Math.max(1080, 1920) : Math.min(1080, 1920))
    const rW = win.width / (isPortal ? Math.min(1080, 1920) : Math.max(1080, 1920))
    
    const boundingLeft = barcode.cornerPoints['0'].x * rW
    const boundingRight = barcode.cornerPoints['1'].x * rW
    const boundingTop = barcode.cornerPoints['0'].y * rH
    const boundingBottom = barcode.cornerPoints['2'].y * rH
    
    const vf_bottom = vf_y + vf_height
    const vf_left = vf_x
    const vf_right = vf_x + vf_width
    const vf_top = vf_y
    
    if (
      boundingTop > vf_top &&
      boundingBottom < vf_bottom &&
      boundingLeft > vf_left &&
      boundingRight < vf_right
    ) {
      console.log('scanned')
    }
})
```

Thank you for any feedback

**Comment by karel-suchomel-ed** [comment]
I have managed to get it working correctly.
1. It's important to have the camera fill the entire screen with resizeMode="contain"
2. Then apply the overlay absolutely on top of the camera
3. Use onLayout function on the overlay component to get the x and y coordinates relative to the screen
4. I recreated the useBarcodeScanner hook, to be able to use inject these coordinates into the onBarcodeScanned function, because it's needed in the frameProcessor dependency list
5. Also I needed the frame instance so I passed it as the second argument of the onBarcodeScanned function
6. Inside I have this code:
```
      const handleBarcode = function () {
        barcodes.forEach((barcode) => {
          const isPortal = win.height > win.width
          const rH = win.height / (isPortal ? Math.max(frame.height, frame.width) : Math.min(frame.height, frame.width))
          const rW = win.width / (isPortal ? Math.min(frame.height, frame.width) : Math.max(frame.height, frame.width))

          const boundingLeft = barcode.boundingBox.origin.x * rW
          const boundingRight = (barcode.boundingBox.origin.x + barcode.boundingBox.size.width) * rW
          const boundingTop = barcode.boundingBox.origin.y * rH
          const boundingBottom = (barcode.boundingBox.origin.y + barcode.boundingBox.size.height) * rH

          const vf_bottom = overlayPosition.y + Math.min(vf_height, 310)
          const vf_left = overlayPosition.x
          const vf_right = vf_left + Math.min(vf_width, 310)
          const vf_top = overlayPosition.y

          if (
            boundingTop > vf_top &&
            boundingBottom < vf_bottom &&
            boundingLeft > vf_left &&
            boundingRight < vf_right
          ) {
            console.log('scanned')
          }
        })
      }

      if (!isScanned.current && barcodes.length > 0) {
        handleBarcode()
      }
```
vf_width and vf_height are the dimensions of the overlay window

Hope it helps, feel free to give feedback or leave a better solution, but for me this is enough

**Comment by DevUser0491** [comment]
Hello @karel-suchomel-ed,
Please, could you explain a little bit more or share an example code?
What are the values: window.height, window.width, overlayHeight, overlayWidth?
The function handleBarcode comes from props or inside a hook useBarcodeScanner?
Like this?
```
const { props: cameraProps, highlights } = useBarcodeScanner({
  fps: 5,
  barcodeTypes: ['qr'],
  onBarcodeScanned: (barcodes, frame) => {
    'worklet';
    
    handleBarcode(barcodes);
    
    console.log(
      `Scanned ${barcodes.length} codes with values=${JSON.stringify(
        barcodes
      )} !`
    );
  },
});
```

**Comment by karel-suchomel-ed** [comment]
Hi @DevUser0491 ,
I no longer use this functionality as we switched it to manual activation by button press, so limiting the scan area was no longer needed.
![IMG_0830](https://github.com/mgcrea/vision-camera-barcode-scanner/assets/91547224/05ad8d62-c92a-45ff-b1c3-9048f4555847)

However, in the useBarcodeScanner hook itself is now a prop called regionOfInterest, which should help you achieve that.

1. window.height and window.width are values from the React Native Dimensions API:


1. window.height and window.width are values from the React Native Dimensions API:
`const window = Dimensions.get('window')`
and overlayWidth and overlayHeight are the dimensions of the overlay area for example 200x200 square
2. handleBarcode was defined inside of the onBarcodeScanned
