### ISSUE TITLE
Scanner crashes when running with react-native-vision-camera v4

### ISSUE THREAD

**Issue by seanpcoyle** [mgcrea/vision-camera-barcode-scanner#29]
**Note:** A previous edit of this ticket addressed some import-related issues that I believe can safely be ignored.

When attempting to load the scanner **using react-native-vision-camera v4**, I encounter an error thrown from this library:
```
NSInvalidArgumentException: -[__NSFrozenArrayM objectForKey:]: unrecognized selector sent to instance 0x302535c50
```
It's not immediately apparent to me where from within the plugin this error is being thrown.

I also encounter the error:
```
Camera.onError(parameter/invalid-parameter): The value "native" could not be parsed to type pixelFormat! [parameter/invalid-parameter: The value "native" could not be parsed to type pixelFormat!]
```

The [release notes for Vision Camera V4 indicate](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0) that "native" is no longer supported.

**Comment by seanpcoyle** [comment]
After some more investigation, it looks as if [this PR](https://github.com/mgcrea/vision-camera-barcode-scanner/pull/19/files) [didn't make it into 0.10.1](https://github.com/mgcrea/vision-camera-barcode-scanner/blob/0.10.1/ios/CodeScannerProcessorPlugin.m). That seems to fix things.

**Comment by seanpcoyle** [comment]
@mgcrea Would it be possible to have a release cut that includes #19? It appears 0.11.0 doesn't include it.

**Comment by tfcornerstone** [comment]
@mgcrea Any progress on this issue?

**Comment by mgcrea** [comment]
Landed in https://github.com/mgcrea/vision-camera-barcode-scanner/releases/tag/0.11.2
