### ISSUE TITLE
Build fails when using with Vision Camera V3

### ISSUE THREAD

**Issue by Nandha-d3v** [mgcrea/vision-camera-barcode-scanner#9]
Here is the issue when I'm trying to run with Vision Camera V3 
`> **Task :mgcrea_vision-camera-barcode-scanner:compileDebugJavaWithJavac FAILED**
79 actionable tasks: 22 executed, 57 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

/Users/CheckV3/node_modules/@mgcrea/vision-camera-barcode-scanner/android/src/main/java/com/visioncameracodescanner/CodeScannerProcessorPlugin.java:20: error: package com.mrousavy.camera.parsers does not exist
import com.mrousavy.camera.parsers.Orientation;
                                  ^
/Users/CheckV3/node_modules/@mgcrea/vision-camera-barcode-scanner/android/src/main/java/com/visioncameracodescanner/CodeScannerProcessorPlugin.java:30: error: constructor FrameProcessorPlugin in class FrameProcessorPlugin cannot be applied to given types;
  public CodeScannerProcessorPlugin() {
                                      ^
  required: Map<String,Object>
  found: no arguments
  reason: actual and formal argument lists differ in length
/Users/CheckV3/node_modules/@mgcrea/vision-camera-barcode-scanner/android/src/main/java/com/visioncameracodescanner/CodeScannerProcessorPlugin.java:68: error: package Orientation does not exist
      Orientation.Companion.fromUnionValue(frame.getOrientation()).toDegrees()
                 ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mgcrea_vision-camera-barcode-scanner:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s`

Other dependency versions are as follows
```
    "@mgcrea/vision-camera-barcode-scanner": "^0.5.1",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-reanimated": "^3.5.4",
    "react-native-vision-camera": "^3.5.1",
    "react-native-worklets-core": "^0.2.2"
```

**Comment by mgcrea** [comment]
Should be fixed with https://github.com/mgcrea/vision-camera-barcode-scanner/releases/tag/0.6.0
